# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these against https://fabricmc.net/develop/ if a build fails --
# these move fast and this file may be a little out of date by the time you build.
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.12

# Mod Properties
mod_version=0.2.0
maven_group=com.musicdiscs
archives_base_name=musicdiscs

# Dependencies
fabric_version=0.158.0+26.2
